[theme]
# Smith & Williams Trucking Theme
primaryColor = "#DC2626"           # Red
backgroundColor = "#000000"        # Black
secondaryBackgroundColor = "#1a1a1a" # Dark Gray
textColor = "#ffffff"              # White
font = "sans serif"

[server]
# Server Configuration
maxUploadSize = 200                # Max file upload size in MB
enableCORS = true
enableXsrfProtection = false
headless = true                     # Required for cloud deployment

[browser]
# Browser Settings
gatherUsageStats = false           # Privacy
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
# Runner Settings
magicEnabled = true
fastReruns = true

[client]
# Client Settings
showErrorDetails = false           # Hide errors in production
toolbarMode = "minimal"            # Clean interface

[deprecation]
# Disable deprecation warnings in production
showPyplotGlobalUse = false